### ISSUE TITLE
Compilation requirements

### ISSUE THREAD

**Issue by thirs** [mmehnert/akonadimailsearch#1]
Hi,

Compilation fails here, with last few lines copied below. Upshot is that some file named boost/shared_ptr.hpp is missing. I'm on a Debian with kdepimlibs5-dev installed. Probably I should install something more, but what?

Thanks in advance for your answer!
Tom

Log:

Scanning dependencies of target akonadimailsearch_automoc
Generating moc_akonadimailsearch.cpp
[  0%] Built target akonadimailsearch_automoc
Scanning dependencies of target akonadimailsearch
[ 33%] Building CXX object src/CMakeFiles/akonadimailsearch.dir/akonadimailsearch_automoc.o
In file included from /usr/include/akonadi/item.h:28:0,
                 from /usr/include/akonadi/contact/contactsearchjob.h:27,
                 from /home/thirs/systeme/addresses/akonadimailsearch/build/src/../../src/akonadimailsearch.h:26,
                 from /home/thirs/systeme/addresses/akonadimailsearch/build/src/moc_akonadimailsearch.cpp:9,
                 from /home/thirs/systeme/addresses/akonadimailsearch/build/src/akonadimailsearch_automoc.cpp:4:
/usr/include/akonadi/itempayloadinternals_p.h:29:32: fatal error: boost/shared_ptr.hpp: No such file or directory
 #include <boost/shared_ptr.hpp>
                                ^
compilation terminated.
src/CMakeFiles/akonadimailsearch.dir/build.make:54: recipe for target 'src/CMakeFiles/akonadimailsearch.dir/akonadimailsearch_automoc.o' failed
make[2]: **\* [src/CMakeFiles/akonadimailsearch.dir/akonadimailsearch_automoc.o] Error 1
CMakeFiles/Makefile2:107: recipe for target 'src/CMakeFiles/akonadimailsearch.dir/all' failed
make[1]: **\* [src/CMakeFiles/akonadimailsearch.dir/all] Error 2
Makefile:123: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by mmehnert** [comment]
Looks like you are missing the libboost development files.
Just check which package on your system contains boost/shared_ptr.hpp. 
For debian that would be e.g. libboost1.58-dev:amd64
